// src/components/BlackHackPricesGenerator.tsx
import { useStore } from '@nanostores/react';
import { useEffect, useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { parse, serialize, type PricesState } from '@/data/the-black-hack/prices-codec';
import type { PriceCategory, PriceItem, PriceTable } from '@/data/types';
import {
  createPricesStore,
  itemPrice,
  type PricesRolls,
} from '@/stores/the-black-hack-prices-store';

const STORAGE_KEY = 'the-black-hack:prices';

interface Props {
  table: PriceTable;
}

export function BlackHackPricesGenerator({ table }: Props) {
  // useMemo гарантирует, что стор создаётся один раз на жизнь компонента.
  const store = useMemo(() => createPricesStore(table), [table]);
  const settlement = useStore(store.$settlement);
  const seed = useStore(store.$seed);
  const rolls = useStore(store.$rolls);
  // До инициализации эффект синхронизации молчит — иначе дефолтный стейт
  // перезатёр бы входящий из URL/localStorage.
  const [initialized, setInitialized] = useState(false);

  // Инициализация на клиенте (не в store-init — SSR-снепшот без цен, hydration не ломается).
  // Источник по приоритету: URL → localStorage → свежий бросок (KTD2 плана).
  useEffect(() => {
    if (store.$seed.get() === null) {
      const state = parse(window.location.search, table) ?? readStorage(table);

      if (state) {
        store.hydrate(state);
      } else {
        store.rollAll();
      }
    }

    setInitialized(true);
  }, [store, table]);

  // Каждое изменение стейта — в оба синка (R10): URL через replaceState (KTD3),
  // localStorage той же canonical-строкой (KTD4).
  useEffect(() => {
    if (!initialized || seed === null) return;
    const query = serialize({ settlement, seed }, table);

    const params = new URLSearchParams(window.location.search);

    for (const [key, value] of new URLSearchParams(query)) {
      params.set(key, value);
    }

    history.replaceState(null, '', `${window.location.pathname}?${params}${window.location.hash}`);

    try {
      window.localStorage.setItem(STORAGE_KEY, query);
    } catch {
      console.warn('localStorage недоступен — цены сохранятся только в URL');
    }
  }, [initialized, settlement, seed, table]);

  const handleSettlementChange = (next: string | number | null) => {
    const selected = table.settlements.find((candidate) => candidate === next);

    if (selected !== undefined) store.setSettlement(selected);
  };

  const visibleCategories = table.settlementCategories[settlement];

  return (
    <div className="space-y-8">
      <div className="space-y-3">
        <span className="font-mono text-xs uppercase tracking-wider text-text-muted">
          Тип поселения
        </span>
        <Tabs value={settlement} onValueChange={handleSettlementChange}>
          <TabsList>
            {table.settlements.map((s) => (
              <TabsTrigger key={s} value={s}>
                {table.settlementLabels[s]}
              </TabsTrigger>
            ))}
          </TabsList>
        </Tabs>
      </div>

      <Button size="lg" onClick={store.rollAll} data-testid="roll-button">
        Перебросить всё
      </Button>

      {table.categories.map((category, categoryIndex) =>
        visibleCategories.includes(category.key) ? (
          <CategorySection
            key={category.key}
            category={category}
            rolls={rolls ? (rolls[categoryIndex] ?? null) : null}
          />
        ) : null,
      )}
    </div>
  );
}

function readStorage(table: PriceTable): PricesState | null {
  try {
    return parse(window.localStorage.getItem(STORAGE_KEY) ?? '', table);
  } catch {
    return null;
  }
}

interface CategorySectionProps {
  category: PriceCategory;
  rolls: PricesRolls[number] | null;
}

function CategorySection({ category, rolls }: CategorySectionProps) {
  const { count, sides } = category.roll;
  const formula = `${count}к${sides}${category.multiplier > 1 ? `×${category.multiplier}` : ''}`;

  return (
    <section data-testid={`category-${category.key}`}>
      <h3 className="font-mono text-xs uppercase tracking-wider text-text-muted">
        {category.ru} · {formula} монет
      </h3>
      <div className="mt-3 overflow-x-auto">
        <table className="w-full border-collapse text-sm">
          <tbody>
            {category.items.map((item, itemIndex) => (
              <PriceRow
                key={item.ru}
                category={category}
                item={item}
                faces={rolls ? (rolls[itemIndex] ?? null) : null}
              />
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

interface PriceRowProps {
  category: PriceCategory;
  item: PriceItem;
  faces: readonly number[] | null;
}

function PriceRow({ category, item, faces }: PriceRowProps) {
  return (
    <tr className="border-b border-border last:border-0">
      <td className="px-2 py-1.5 text-text">
        {item.ru}
        {item.note ? (
          <span className="ml-2 font-mono text-xs text-text-muted">{item.note}</span>
        ) : null}
      </td>
      <td className="px-2 py-1.5 text-right font-mono" data-testid="item-price">
        <Skeleton loading={faces === null}>
          {faces ? itemPrice(faces, category, item) : 0} мон.
        </Skeleton>
      </td>
    </tr>
  );
}

// src/components/BlackHackPricesGenerator.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Button from '@/components/ui/button.svelte';
  import Skeleton from '@/components/ui/skeleton.svelte';
  import Tabs from '@/components/ui/tabs.svelte';
  import TabsList from '@/components/ui/TabsList.svelte';
  import TabsTrigger from '@/components/ui/TabsTrigger.svelte';
  import { parse, serialize, type PricesState } from '@/data/the-black-hack/prices-codec';
  import type { PriceCategory, PriceItem, PriceTable } from '@/data/types';
  import {
    createPricesStore,
    itemPrice,
    type PricesRolls,
  } from '@/stores/the-black-hack-prices-store';

  const STORAGE_KEY = 'the-black-hack:prices';

  const { table }: { table: PriceTable } = $props();

  // svelte-ignore state_referenced_locally (Astro passes static table data; live table swaps should remount with a key.)
  const store = createPricesStore(table);

  const settlementStore = store.$settlement;

  const seedStore = store.$seed;

  const rollsStore = store.$rolls;

  let initialized = $state(false);

  let settlement = $derived($settlementStore);

  let seed = $derived($seedStore);

  let rolls = $derived($rollsStore);

  let visibleCategories = $derived(table.settlementCategories[settlement]);

  function readStorage(): PricesState | null {
    try {
      const value = window.localStorage.getItem(STORAGE_KEY);

      return value ? parse(value, table) : null;
    } catch {
      return null;
    }
  }

  onMount(() => {
    if (store.$seed.get() === null) {
      const state = parse(window.location.search, table) ?? readStorage();

      if (state) {
        store.hydrate(state);
      } else {
        store.rollAll();
      }
    }

    initialized = true;
  });

  $effect(() => {
    if (!initialized || seed === null) return;
    const query = serialize({ settlement, seed }, table);

    const params = new URLSearchParams(window.location.search);

    for (const [key, value] of new URLSearchParams(query)) {
      params.set(key, value);
    }

    history.replaceState(null, '', `${window.location.pathname}?${params}${window.location.hash}`);

    try {
      window.localStorage.setItem(STORAGE_KEY, query);
    } catch {
      console.warn('localStorage недоступен — цены сохранятся только в URL');
    }
  });

  function setSettlement(next: string | number) {
    const selected = table.settlements.find((candidate) => candidate === next);

    if (selected !== undefined) store.setSettlement(selected);
  }

  function categoryRolls(allRolls: PricesRolls | null, categoryIndex: number) {
    return allRolls ? allRolls[categoryIndex] : null;
  }

  function priceText(category: PriceCategory, item: PriceItem, faces: readonly number[] | null) {
    return `${faces ? itemPrice(faces, category, item) : 0} мон.`;
  }
</script>

<div class="space-y-8">
  <div class="space-y-3">
    <span class="font-mono text-xs uppercase tracking-wider text-text-muted">Тип поселения</span>
    <Tabs value={settlement} onValueChange={setSettlement}>
      <TabsList>
        {#each table.settlements as s (s)}
          <TabsTrigger value={s}>{table.settlementLabels[s]}</TabsTrigger>
        {/each}
      </TabsList>
    </Tabs>
  </div>

  <Button size="lg" onclick={store.rollAll} data-testid="roll-button">Перебросить всё</Button>

  <div class="space-y-8">
    {#each table.categories as category, categoryIndex (category.key)}
      {#if visibleCategories.includes(category.key)}
        {@const categoryFaces = categoryRolls(rolls, categoryIndex)}
        {@const formula = `${category.roll.count}к${category.roll.sides}${category.multiplier > 1 ? `×${category.multiplier}` : ''}`}
        <section data-testid={`category-${category.key}`}>
          <h3 class="font-mono text-xs uppercase tracking-wider text-text-muted">
            {category.ru} · {formula} монет
          </h3>
          <div class="mt-3 overflow-x-auto">
            <table class="w-full border-collapse text-sm">
              <tbody>
                {#each category.items as item, itemIndex (itemIndex)}
                  {@const faces = categoryFaces ? categoryFaces[itemIndex] : null}
                  <tr class="border-b border-border last:border-0">
                    <td class="px-2 py-1.5 text-text">
                      {item.ru}
                      {#if item.note}
                        <span class="ml-2 font-mono text-xs text-text-muted">{item.note}</span>
                      {/if}
                    </td>
                    <td class="px-2 py-1.5 text-right font-mono" data-testid="item-price">
                      <Skeleton loading={faces === null}
                        >{priceText(category, item, faces)}</Skeleton
                      >
                    </td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        </section>
      {/if}
    {/each}
  </div>
</div>
