// src/components/ReferenceList.tsx
import type { ReactNode } from 'react';

interface Props<Row> {
  title: string;
  testId: string;
  rows: readonly Row[];
  hitIndex: number | null;
  label: (row: Row, index: number) => ReactNode;
  children: (row: Row) => ReactNode;
}

export function referenceHitClass(isHit: boolean): string {
  return isHit ? 'border-l-2 border-primary bg-primary/10 text-text' : 'text-text-muted';
}

export function ReferenceList<Row>({ title, testId, rows, hitIndex, label, children }: Props<Row>) {
  return (
    <section data-testid={testId}>
      <h3 className="font-mono text-xs uppercase tracking-wider text-text-muted">{title}</h3>
      <ul className="mt-3 grid grid-cols-[max-content_1fr] divide-y divide-border">
        {rows.map((row, i) => (
          <li
            key={i}
            data-row-index={i}
            data-hit={i === hitIndex ? 'true' : undefined}
            className={`col-span-2 grid grid-cols-subgrid gap-3 px-2 py-1.5 ${referenceHitClass(i === hitIndex)}`}
          >
            <span className="font-mono text-xs">{label(row, i)}</span>
            <span className="text-sm">{children(row)}</span>
          </li>
        ))}
      </ul>
    </section>
  );
}

// src/components/ReferenceList.svelte
<script lang="ts" generics="Row">
  import type { Snippet } from 'svelte';

  interface Props {
    title: string;
    testId: string;
    rows: readonly Row[];
    hitIndex: number | null;
    label: Snippet<[Row, number]>;
    children: Snippet<[Row]>;
  }

  let { title, testId, rows, hitIndex, label, children }: Props = $props();

  export function referenceHitClass(isHit: boolean): string {
    return isHit ? 'border-l-2 border-primary bg-primary/10 text-text' : 'text-text-muted';
  }
</script>

<section data-testid={testId}>
  <h3 class="font-mono text-xs uppercase tracking-wider text-text-muted">{title}</h3>
  <ul class="mt-3 grid grid-cols-[max-content_1fr] divide-y divide-border">
    {#each rows as row, i}
      <li
        data-row-index={i}
        data-hit={i === hitIndex ? 'true' : undefined}
        class={`col-span-2 grid grid-cols-subgrid gap-3 px-2 py-1.5 ${referenceHitClass(i === hitIndex)}`}
      >
        <span class="font-mono text-xs">{@render label(row, i)}</span>
        <span class="text-sm">{@render children(row)}</span>
      </li>
    {/each}
  </ul>
</section>
